<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{e78bea8e-16ce-4fbf-9199-261b888cbbef}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nfeature:INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nfeature:= nfeature + 1;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>